### PR TITLE
Put a spinner in Experiments view if experiment data is still loading

### LINKED ISSUE #600: Display "update in progress" instead of "no data"
When looking at a project, "no data" message is incorrectly displayed until the list is populated. Show a spinner here instead.

### PR DESCRIPTION
**Pull request by annehaley**
Resolves #600

### CODE REVIEW

File: web_client/src/components/ExperimentsView.vue [hunk 1]
```diff
@@ -280,6 +280,13 @@ export default {
           </li>
         </ul>
       </div>
+      <div
+        v-else-if="currentProject.experiments.length"
```
Comment (zachmullen) [inline web_client/src/components/ExperimentsView.vue:284]: Shouldn't we use an out-of-band `loading: boolean` state for this? What if the project simply has no experiments yet?

Comment (annehaley) [reply web_client/src/components/ExperimentsView.vue:284]: If the project has no experiments, the `v-else-if` directive will evaluate to false and the `v-else` block will show "No imported data"

Comment (zachmullen) [reply web_client/src/components/ExperimentsView.vue:284]: Oh, I see. Thanks for the explanation.

**Review by zachmullen — APPROVED** [review]
